prettyPrint: true
openAPI:
  info:
    title: Arrowhead System Registry Core System API
    description: 'This page shows the REST interfaces offered by the System Registry Core System.'
    contact:
      url: https://github.com/arrowhead-f