prettyPrint: true
openAPI:
  info:
    title: Arrowhead Certificate Authority Core System API
    description: 'This page shows the REST interfaces offered by the Certificate Authority Core System.'
    contact:
      url: https://github.com/arrowhead-f