prettyPrint: true
openAPI:
  info:
    title: Arrowhead Onboarding Core System API
    description: 'This page shows the REST interfaces offered by the Onboarding System.'
    contact:
      url: https://github.com/arrowhead-f